### ISSUE TITLE
Plusieurs appels à top bloque le client

### ISSUE THREAD

**Issue by matthieu637** [matthieu637/cpp-2a-info#24]
```
r=Reseau()
r.creerPartie('a')
r.top()
r.top()
>>> -4
r.ventes('Trydea')
>>> -4 # pas normal
r.nomAction
>>> ['apple',
 'apple',
 'facebook',
 'facebook',
 'google',
 'google',
 'trydea',
 'trydea'] # trop d'action dans la liste
```

**Comment by david540** [comment]
En effet, il y a un gros problème parce qu'à chaque appel de "top",
les actions sont ajoutées une deuxième fois à la liste r.nomAction, et la liste histoActions et le temps côté client sont remis à zéro..
Après le tri dans r.top() on a la liste que l'on voit dans l'issue après appel de r.nomAction
Donc après un deuxième appel de r.top(), et après appel de r.ventes("Trydea") l'indice récupéré par __chercherNumAction("Trydea") renvoie 6 ou 7 et l'envoie au serveur.
C'est le test côté serveur: if (arg < nombreActions && arg >= 0) {...} else envoyer(out,-4);
qui est responsable du -4 envoyé par le serveur car nombreActions=4<arg=6 
C'est pour celà que r.ventes('Trydea') retourne -4

Donc il suffit d'ajouter un 	if self.__topbool: return -4  au début de la fonction top, le bug n'est pas plus profond que celà, je vais faire le pull request
